name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: 显示版本
      run: |
        echo "系统版本:" $(uname -a)
        echo "发行版本:" $(cat /etc/os-release)
        echo "docker 版本:" $(docker --version)

    - name: 登录阿里云镜像仓库
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALI_DOCKER_USERNAME }}
        password: ${{ secrets.ALI_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com

    - name: 推送镜像 python 镜像
      run: |
        sh src/sync.sh data/python.txt

    - name: 推送镜像 k8s 镜像
      run: |
        sh src/sync.sh data/k8s.txt
